// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsScrapingMonolithic.Persistence.Context;

#nullable disable

namespace NewsScrapingMonolithic.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240228003215_AddHostsTable")]
    partial class AddHostsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.EmailHost", b =>
                {
                    b.Property<Guid>("EmailId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("EmailId", "HostId");

                    b.HasIndex("HostId");

                    b.ToTable("EmailHosts");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Host");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.EmailHost", b =>
                {
                    b.HasOne("NewsScrapingMonolithic.Domain.Entities.Email", "Email")
                        .WithMany("Hosts")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsScrapingMonolithic.Domain.Entities.Host", "Host")
                        .WithMany("Emails")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.Email", b =>
                {
                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.Host", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
