// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsScrapingMonolithic.Persistence.Context;

#nullable disable

namespace NewsScrapingMonolithic.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260822230042_RenameHostToNewsPage")]
    partial class RenameHostToNewsPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmailNewsPage", b =>
                {
                    b.Property<Guid>("EmailsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HostsId")
                        .HasColumnType("char(36)");

                    b.HasKey("EmailsId", "HostsId");

                    b.HasIndex("HostsId");

                    b.ToTable("EmailNewsPage");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("NewsScrapingMonolithic.Domain.Entities.NewsPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("HeaderHost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("NewsPages");
                });

            modelBuilder.Entity("EmailNewsPage", b =>
                {
                    b.HasOne("NewsScrapingMonolithic.Domain.Entities.Email", null)
                        .WithMany()
                        .HasForeignKey("EmailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsScrapingMonolithic.Domain.Entities.NewsPage", null)
                        .WithMany()
                        .HasForeignKey("HostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
